"""empty message

Revision ID: af50254ba7bb
Revises: e53ad3fe13fd
Create Date: 2020-02-21 11:35:21.520904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af50254ba7bb'
down_revision = 'e53ad3fe13fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('User_ID', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'User_ID')
    # ### end Alembic commands ###
