"""empty message

Revision ID: e53ad3fe13fd
Revises: 
Create Date: 2020-01-07 22:57:49.945920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53ad3fe13fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order',
    sa.Column('OrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Delivery_name', sa.String(length=256), nullable=True),
    sa.Column('User_name', sa.String(length=256), nullable=True),
    sa.Column('Area', sa.String(length=128), nullable=True),
    sa.Column('Receipt_time', sa.String(length=128), nullable=True),
    sa.Column('Delivery_time', sa.String(length=128), nullable=True),
    sa.Column('Limit', sa.String(length=64), nullable=True),
    sa.Column('Place', sa.String(length=256), nullable=True),
    sa.Column('Check', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('OrderDetail',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('User_name', sa.String(length=256), nullable=True),
    sa.Column('Store_name', sa.String(length=256), nullable=True),
    sa.Column('Product', sa.String(length=256), nullable=True),
    sa.Column('Quantity', sa.String(length=32), nullable=True),
    sa.Column('UserID', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['Order.OrderID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderDetail')
    op.drop_table('Order')
    # ### end Alembic commands ###
